### ISSUE TITLE
Generate default meaningful response description based on http_code

### ISSUE THREAD

**Issue by Fatal1ty** [Fatal1ty/openapify#1]
**Is your feature request related to a problem? Please describe.**
Decorator `@response_schema` should apply default response description instead of `None`.

**Describe the solution you'd like**
We can take messages from here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by sabbirtkdr** [comment]
@Fatal1ty Hi I am new to opensource contributions, I am willing to contribute to this issue, if its okay. Could you inform me more about this issue?

**Comment by Fatal1ty** [comment]
> @Fatal1ty Hi I am new to opensource contributions, I am willing to contribute to this issue, if its okay. Could you inform me more about this issue?

Thank you for your interest. I did it quickly myself, but there will be more issues which you can contribute to!

**Comment by sabbirtkdr** [comment]
Thank you, could you point me to some "Good first issue(s)" so that I can add my contribution?

**Comment by Fatal1ty** [comment]
> Thank you, could you point me to some "Good first issue(s)" so that I can add my contribution?

You can start with this list https://github.com/topics/good-first-issue
