### ISSUE TITLE
APIKeySecurityScheme doesn't have serialize_by_alias = True

### ISSUE THREAD

**Issue by Annegies** [Fatal1ty/openapify#4]
* openapify version: 0.3.8
* Python version:   3.10.12
* Operating System: Linux

### Description

I'm creating an Open Api Spec with an API key, so i'm using the `APIKeySecurityScheme ` model.
However when building it the result is 
```
"securitySchemes": {
      "APIKeyHeader": {
        "type": "apiKey",
        "name": "Authorization",
        "location": "header",
        "description": ""
      }
    }
```
And following the spec "location" should be "in" .

### What I Did

```
        api_token_requirement = {
            "APIKeyHeader": APIKeySecurityScheme(
                name="Authorization",
                location=SecuritySchemeAPIKeyLocation.HEADER,
                description="",
            )
        }
```

**Comment by Fatal1ty** [comment]
Good catch! It will be very easy to fix.

**Comment by Fatal1ty** [comment]
Version 0.3.9 is now published https://pypi.org/project/openapify/
